### ISSUE TITLE
Push package to nuget.org

### ISSUE THREAD

**Issue by d-dizhevsky** [AvaloniaUI/avalonia-dotnet-templates#10]
Please consider pushing `Avalonia.Templates.NetCore` package to nuget.org. It will give us an ability to use command like `dotnet new --install Avalonia.Templates.NetCore` to get a template without cloning the whole repo.

**Comment by kunjee17** [comment]
Getting stared guide is having that command but seems it is not there on nuget. I did filed an [issue](https://github.com/AvaloniaUI/Avalonia/issues/1467) . Hope things got sorted out soon...

**Comment by rstm-sf** [comment]
That was done https://www.nuget.org/packages/Avalonia.Templates/
