### ISSUE TITLE
Make templates fully usable from VS

### ISSUE THREAD

**Issue by Takoooooo** [AvaloniaUI/avalonia-dotnet-templates#108]
Apparently, it is possible to fully remove templates from vsix and just customize CLI templates in the way they can be used from VS. It would save us a lot of time since currently we need to update templates twice. One in this repo,once in AvaloniaVS.
Materials:
https://learn.microsoft.com/en-us/shows/visual-studio-toolbox/add-a-parameter-to-a-net-core-project-template

**Comment by Mrxx99** [comment]
But it would be a bad experience if by installing the VS extension, you would not get any templates.
Also besides than having to install the templates separately I think you still would need to go to Visual Studio settings first to enable that CLI templates are shown in VS (or is this now the default?)

**Comment by Takoooooo** [comment]
> But it would be a bad experience if by installing the VS extension, you would not get any templates. Also besides than having to install the templates separately I think you still would need to go to Visual Studio settings first to enable that CLI templates are shown in VS (or is this now the default?)

Replied here https://github.com/AvaloniaUI/AvaloniaVS/pull/267#issuecomment-1332033329
