### ISSUE TITLE
Rename current "Avalonia MVVM" template into "Avalonia MVVM ReactiveUI" and avoid RxUI in other templates

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/avalonia-dotnet-templates#110]
Not everybody likes the ReactiveUI. Some people would prefer community toolkit framework.
Also, we shouldn't force people to use MVVM template at all.

**Comment by maximilien-noal** [comment]
My experience with Avalonia improved greatly since I ditched the over-engineeered ReactiveUI for the MVVM Community Toolkit.

Just replace ReactiveUI with the MVVM Community Toolkit.

**Comment by maxkatz6** [comment]
"Avalonia MVVM" template now have an option to switch between RxUI and MVVM toolkit:
https://github.com/AvaloniaUI/avalonia-dotnet-templates/blob/master/templates/csharp/app-mvvm/AvaloniaAppTemplate.csproj https://github.com/AvaloniaUI/avalonia-dotnet-templates/blob/master/templates/csharp/app-mvvm/.template.config/template.json#L34
