### ISSUE TITLE
[Optional] Add "Avalonia MVVM CommunityToolkit" framework

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/avalonia-dotnet-templates#111]

**Comment by StarlkYT** [comment]
Can I try to do this?

**Comment by maxkatz6** [comment]
I wonder if we can make it a parameter of the same template. See https://github.com/AvaloniaUI/avalonia-dotnet-templates/issues/108

**Comment by Takoooooo** [comment]
@StarlkYT Make the c# template for the MVVM CommunityToolkit,i may not merge it in the end but it would help me with customizing our templates to support few frameworks at the time. Our main plan is to have one mvvm template where you can select the MVVM framework you want by passing an argument. I am not finished investigating on how people do that but at the moment I am totally sure it is possible,and if you will make the template I may use it as the reference when customizing the original template

**Comment by StarlkYT** [comment]
> @StarlkYT Make the c# template for the MVVM CommunityToolkit,i may not merge it in the end but it would help me with customizing our templates to support few frameworks at the time. Our main plan is to have one mvvm template where you can select the MVVM framework you want by passing an argument. I am not finished investigating on how people do that but at the moment I am totally sure it is possible,and if you will make the template I may use it as the reference when customizing the original template

I will create it in a separate branch so that it is easier for you to see it

**Comment by Mrxx99** [comment]
I think that can be closed, as the MVVM CommunityToolkit is now supported.
