### ISSUE TITLE
[Discussion] Decide if we need to make xplat template target macos and windows target frameworks

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/avalonia-dotnet-templates#112]
Without that developers would continue to be confused with how to access native APIs.
Alternatively, we can write small docs about it.

**Comment by Takoooooo** [comment]
I don't think we really need to add 3 additional projects to support that,maybe we can add a parameter for that because it may be useful for someone but for now i think just adding a comment would be sufficient
