### ISSUE TITLE
Windows on Arm / DevKit 2023 can't install Avalonia.Templates

### ISSUE THREAD

**Issue by olifink** [AvaloniaUI/avalonia-dotnet-templates#124]
**Describe the bug**
`dotnet new install Avalonia.Templates` fails on Windows on Arm / Voltera / Windows DevKit 2023

**To Reproduce**
on Windows 11 on Arm machine: open console, enter above command, observe error message

**Expected behavior**
on Windows 11 Intel x86_64 machine this is successful

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows Arm 64
- Version 22623.875

**Additional context**
same failure during `dotnet restore` on Avalonia packages used in existing source code package that builds fine on other systems. (Also, arm64 Avalonia apps like Lunacy only shows black window on this machine)

**Comment by maxkatz6** [comment]
Please add the error message.
It also might .NET SDK bug. Can you try to install any other third-party template?

**Comment by maxkatz6** [comment]
> same failure during dotnet restore on Avalonia packages used in existing source code package that builds fine on other systems.

And error message for that as well.

**Comment by olifink** [comment]
oops. sorry - indeed my bad - it appears `nuget.org` wasn't registered as a package source. Now at least it installs and build, now it just crashes when creating a window as reported by others already.

```
System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```
