### ISSUE TITLE
.Net core cli bug

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaUI/avalonia-dotnet-templates#129]
Print
` dotnet new avalonia.usercontrol -p:n Control -n Scene`

Have

```cs
namespace AvaloniaAppTemplate.Namespace
{
    public partial class Scene : UserControl
    {
```

Incorrect namescpace

**To Reproduce**

`<PackageReference Include="Avalonia" Version="0.10.18"/>`

**Comment by CreateLab** [comment]
namespace Controls

**Comment by maxkatz6** [comment]
I don't see any information about namespaces or "-p:n" parameter in the templates documentation https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new

I guess it's something that needs to be handled by the template specifically?

**Comment by Takoooooo** [comment]
I am guessing it was deprecated by MS,i don't think that something that we have broken

**Comment by Takoooooo** [comment]
I am guessing that it is the issue in the some of SDK's. Tried to repro that with the `` dotnet new avalonia.usercontrol -p:n Control -n Scene`` with 7.0.101 SDK and i got 
![image](https://user-images.githubusercontent.com/53405089/211544642-49e08707-64fb-41b8-8e39-ce3bc504e852.png)
which is expected i think
