### ISSUE TITLE
MainWindow.xaml.cs to include Avalonia.Interactivity by default

### ISSUE THREAD

**Issue by dzmitry-lahoda** [AvaloniaUI/avalonia-dotnet-templates#13]
I was easy to get up and running, but handle Button Click  have to `using Avalonia.Interactivity`. I think started should include that important namespace by default.

**Comment by Takoooooo** [comment]
Sorry, i don't see any purpose in adding that I think that you need to have in the project by default only using that are being actually used. Feel free to reopen the issue if you don't agree.
