### ISSUE TITLE
How to create a Cross-Platform Avalonia app, but to specify Avalonia version?

### ISSUE THREAD

**Issue by tivewsalaeharad** [AvaloniaUI/avalonia-dotnet-templates#132]
When I print `dotnet new avalonia.xplat`, dotnet creates app with 11.0.0-preview2 version. Is there a way to create template, based on 0.10.18.2 f.e. version, because CSharpMath (https://github.com/verybadcat/CSharpMath) doesn't work on Avalonia 11.0.0, producing error "Could not load file or assembly 'Avalonia.Visuals, Version=0.10.0.0 ..."
Something like this:
`dotnet new avalonia.xplat -A 0.10.18.2`

**Comment by maxkatz6** [comment]
No. Mobile support was added only in 11.0. Browser support existed in 0.10, but was poor and changed in 11.0.

If you use only desktop, you can use "avalonia.app" or "avalonia.mvvm" templates, they both work on Win, Mac and Lin with no issues.

**Comment by tivewsalaeharad** [comment]
@maxkatz6 Unfortunately, using Avalonia 11.0.0 has some problems:

- CSharpMath doesn't work on Avalonia 11, throwing exception FileNotFound (Could not load file or assembly 'Avalonia.Visuals'). This is very important, I need mathematical formulae in my app
- ListBox.Tapped event cannot be resolved
- NotificationManager.Position property has no effect, notification always appears at top-left

But the way, here: https://docs.avaloniaui.net/tutorials/developing-for-mobile/create-a-cross-platform-solution is written about 0.10.13 version

**Comment by maxkatz6** [comment]
It's a template version number, not the framework.
