### ISSUE TITLE
Remove ViewLocator or hide behind a parameter

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/avalonia-dotnet-templates#177]
Currently ViewLocator in the templates is an easy way to make configure multiple view + view models soltuion. But even then for proper navigation it would require a bit more research and understanding, than simple view locator can give.

On the other side, current view locator is not trimming nor AOT friendly. Making it so would make default template way too complex.

Proposal: in the default templates we should remove view locator. Main view model is already set implicitly on the main window/view by the App.xaml.cs.

**Comment by giopalma** [comment]
Documentation is not updated. 
For example https://docs.avaloniaui.net/tutorials/todo-list-app uses old template with ViewLocator and the tutorial can't be reproduced step-by-step with the new template.
