### ISSUE TITLE
[avalonia.app] Unable to run project

### ISSUE THREAD

**Issue by x1unix** [AvaloniaUI/avalonia-dotnet-templates#18]
### Description
I get NuGet errors when I'm trying to run an app created from Avalonia template.

### Environment

* **OS**: Ubuntu 18.10
* **.NET Core**: 2.2.202

### Steps

* Install .Net Core 2.2 SDK
* Install [avalonia-dotnet-templates](https://github.com/AvaloniaUI/avalonia-dotnet-templates)
* Create a new project: `dotnet new avalonia.app -o avapp`
* Try to run the app: `dotnet run`

When I'm running `dotnet run` I get these errors:
```
Unable to run your project
Your project targets multiple frameworks. Please specify which framework to run using '--framework'.
```

**Comment by kekekeks** [comment]
The created project is targeting both .NET Core and .NETFramework/Mono. You need to choose which target you want to run.

**Comment by Kr3m** [comment]
any recommendations on how to do this before closing this out?  i don't think it would hurt, given that Ubuntu users like me are still debating the usefulness of using C# in our projects period and these bug reports are typically what come up in Google searches.  I mean sure we can always search twice, but you'd think a less generic response would be more appropriate...

**Comment by Kr3m** [comment]
for future reference if anyone runs into this here is one solution.  good lord.  on to step 2 days later....

dotnet run --framework netcoreapp2.2

**Comment by Kr3m** [comment]
Still absolutely useless if you'd like to use Avalon Studio in Ubuntu when you run into this just trying to build the window with a user control view added:

Unable to find file: D:\a\1\s\src\Markup\Avalonia.Markup.Xaml\AvaloniaXamlLoader.cs

So happy command lining......
