### ISSUE TITLE
TemplatedControl should use ControlTheme instead of styles

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/avalonia-dotnet-templates#197]
It's generally better for templated controls to use ControlTheme in Avalonia 11.0.
As build in controls were already migrated as well as some third parties.
Having templates using newer approach will help us with this migration.

Note:
1. It's quite difficult to have file template using Styles for 0.10 and ControlTheme for 11.0, especially when IDE won't have options to select the version.
2. If we go with version, then it's probably better to add an option to opt out from ControlTheme even on 11.0.
3. And it might be easier at this point to have two different templates, as this way IDE experience will be better.

**Comment by Mrxx99** [comment]
@maxkatz6 If an MSBuild property would be auto added to the user project by Build.props file of Avalonia nuget, that declares the Avalonia version (<AvaloniaVersion>11</AvaloniaVersion>, similar like project-capability is set) than this could be used to bind to a property in the item templates (like it is done for the RootNamespace). But this would have to be added best before v11 release. With this we could differentiate the template by version, there could still be a CLI option to use when item template is created outside of project.

Reference: https://github.com/dotnet/templating/wiki/Binding-and-project-context-evaluation#binding-to-msbuild-properties

**Comment by maxkatz6** [comment]
We probably should just add a second template item when we remove 0.10 templates (at some point after 11.0 release).
