### ISSUE TITLE
Group Avalonia templates in Rider "New Project" window

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/avalonia-dotnet-templates#207]
### Is your feature request related to a problem? Please describe.

Avalonia templates are left in the "Other" category, while most of the other templates are grouped properly:

![image](https://github.com/AvaloniaUI/avalonia-dotnet-templates/assets/3163374/c009e307-d98d-4177-b133-eddcbc4b4397)

### Describe the solution you'd like

Avalonia templates should be grouped together in Rider project creation.

**Comment by Mrxx99** [comment]
That's strange I thought I have seen them grouped before in Rider, but not 100% sure.

**Comment by Takoooooo** [comment]
It needs to be supported by Ruder separately,it isn't an issue of our templates
https://youtrack.jetbrains.com/issue/RIDER-95969/Avalonia-templates-are-not-grouped
