### ISSUE TITLE
iOS Templates wont work by default 

### ISSUE THREAD

**Issue by MikeCodesDotNET** [AvaloniaUI/avalonia-dotnet-templates#208]
### Describe the bug

We need to update the iOS template to use NET7 and remove the runtime identifier. 

The csproj should look something like this: 

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0-ios</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
  </PropertyGroup>
</Project>
```

This will then enable deploying to both the simulator and device without needing to edit the csproj. 

### To Reproduce

Create a new iOS Project. Try and deploy it to a device. It won't work. 

### Avalonia Templates version

Latest

### Avalonia version

Latest RC

**Comment by Mrxx99** [comment]
The xplat template already use .NET 7 by default (and can't be changed to .NET 6 with template parameters).
