### ISSUE TITLE
New Avalonia User Control still contains the `private void InitializeComponent()` method

### ISSUE THREAD

**Issue by mozesa** [AvaloniaUI/avalonia-dotnet-templates#224]
### Describe the bug

New Avalonia User Control's code-behind `.axaml.cs` contains `InitializeComponent` method.

```csharp
public partial class UserControl1 : UserControl
{
    public UserControl1()
    {
        InitializeComponent();
    }

    private void InitializeComponent()
    {
        AvaloniaXamlLoader.Load(this);
    }
}
```

### To Reproduce

* Start a new Avalonia .NET MVVM App
* Add a new Avalonia User Control

![image](https://github.com/AvaloniaUI/avalonia-dotnet-templates/assets/49973426/4e615fa7-d900-40e5-bc1d-23cf0579799c)

### Avalonia Templates version

11.0.0

### Avalonia version

11.0.0

**Comment by maxkatz6** [comment]
There is no such method in our templates https://github.com/AvaloniaUI/avalonia-dotnet-templates/blob/master/templates/csharp/usercontrol/NewUserControl.axaml.cs

IIRC, Rider has its own set of templates, and this bug should be reported to them through [youtrack](https://youtrack.jetbrains.com/issues/RIDER).

**Comment by maxkatz6** [comment]
Or I guess it's defined here in AvaloniaRider repository, which we also do not maintain. cc @ForNeVeR
https://github.com/ForNeVeR/AvaloniaRider/blob/7b47af9c8c20c3e742ca179e45bdcdbcd058917f/src/extensions/settings/fileTemplates.DotSettings#L61

**Comment by maxkatz6** [comment]
Created an issue there https://github.com/ForNeVeR/AvaloniaRider/issues/286
