### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by IdkGoodName** [AvaloniaUI/avalonia-dotnet-templates#24]
Using any of AvaloniaUI templates gives an exception.
```
$ dotnet new avalonia.app
Object reference not set to an instance of an object.
```
Seems like field wasn't set somewhere.

**Comment by kekekeks** [comment]
Seems to be an issue with .NET SDK and/or https://github.com/dotnet/templating

**Comment by CreatorVilius** [comment]
It doesn't seem to work on .NET Core 2.2 and .NET Core 3.0 Preview 6 though.
