### ISSUE TITLE
Preparing for 11.1

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/avalonia-dotnet-templates#248]
### Is your feature request related to a problem? Please describe.

Checklist:
- [x] Make xplat.browser compatible with latest SDK and Avalonia - https://github.com/AvaloniaUI/avalonia-dotnet-templates/pull/247
- [x] Delete 0.10 templates - https://github.com/AvaloniaUI/avalonia-dotnet-templates/pull/250
- [x] Make sure all XPlat templates only use .NET 8, previous versions are not supported
- [ ] Remove ReactiveUI from XPlat templates
- [x] Temporary add 11.1.0-beta option
- [x] Decide if we want to keep .NET 7 and 11.0 even as an option, or just force latest (preferable) - UPD: .NET 7 removed, 11.0 was left for now
- [x] New TemplatedControl templates based on ControlTheme - https://github.com/AvaloniaUI/avalonia-dotnet-templates/pull/239

**Comment by Mrxx99** [comment]
Should XPlat templates use MVVM toolkit instead  or no MVVM framework at all?

**Comment by LurkyVAR** [comment]
Sir, is there a timetable for upgrading Avalonia.Template in NuGet?

**Comment by maxkatz6** [comment]
@Mrxx99 personally, I would go with no MVVM framework at all. Possibly just keep ViewModelBase with minimal INotifyPropertyChanged impl and link to our documentation explaining other possibilities.

@LurkyVAR for 11.1? No timeline yet. When it's ready basically.
