### ISSUE TITLE
"Your project targets multiple frameworks.  Please specify which framework to run using '--framework'.

### ISSUE THREAD

**Issue by ashelleyPurdue** [AvaloniaUI/avalonia-dotnet-templates#25]
When using version 0.8.0 of Avalonia, the command "dotnet run" returns the error message written in the issue title.  This is happening on Ubuntu with .Net Core 2.2.300 installed.

This is strange because, as far as I can tell, the only framework being targetted is netcoreapp2.1.

On a possibly-related note, these templates still use netcoreapp2.1, even though the latest is netcoreapp2.2.  They should probably be updated.

**Comment by kekekeks** [comment]
If your `csproj` file has `TargetFrameworks` with `s` at the end, the .NET tooling assumes that it uses multitargeting. If you want to use `dotnet run` without specifying the framework from command line, use `TargetFramework` entry without `s` at the end in your `csproj` file

**Comment by ashelleyPurdue** [comment]
That change should be made to this repo then; that'd make for a more sensible default.

Unfortunately, changing `TargetFrameworks` to `TargetFramework` results in a new error:
`error MSB4022: The result "" of evaluating the value "$(AvaloniaBuildTasksLocation)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.`

So there are probably more changes needed elsewhere.

**Comment by kekekeks** [comment]
Are you, by chance, using VSCode on *nix?

**Comment by ashelleyPurdue** [comment]
Yes I am.

**Comment by kekekeks** [comment]
It's a bug in OmniSharp

**Comment by ashelleyPurdue** [comment]
That error also happens when I use "dotnet run" from the command line though.  Omnisharp isn't involved in that.

**Comment by kekekeks** [comment]
Make sure that you have at least .NET Core SDK  2.2.105 installed

**Comment by kekekeks** [comment]
Try running `dotnet msbuild /bl`. It should produce a binary log file.

**Comment by Takoooooo** [comment]
Works good currently i think,feel free to reopen if it doesn't

**Comment by jgcodes2020** [comment]
> That change should be made to this repo then; that'd make for a more sensible default.
> 
> Unfortunately, changing `TargetFrameworks` to `TargetFramework` results in a new error: `error MSB4022: The result "" of evaluating the value "$(AvaloniaBuildTasksLocation)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.`
> 
> So there are probably more changes needed elsewhere.

I'm getting this issue in Rider, so this isn't just an OmniSharp bug. Can we get this re-opened?

**Comment by maxkatz6** [comment]
No.
A new issue can be created if you provide enough minimal information to reproduce it.
But in general, this error doesn't happen with our templates normally.
