### ISSUE TITLE
Remove ReactiveUI from XPlat templates

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/avalonia-dotnet-templates#252]
### Is your feature request related to a problem? Please describe.

^

### Describe the solution you'd like

Personally, I would go with no MVVM framework at all. Possibly just keep ViewModelBase with minimal INotifyPropertyChanged impl and link to our documentation explaining other possibilities

**Comment by stevemonaco** [comment]
I understand the desire to be more like WPF that only offers the blankest of canvases, but that's pretty inconvenient for end developers. I would probably not use `avalonia-dotnet-templates` anymore and would either: 1. create my own template or 2. find a third-party template provider. I frequently create new Avalonia projects to experiment/verify and the 3-5 minute savings per project with Mvvm Toolkit out-of-the-box does add up. Once I get invested in reinventing part of the wheel, I'm probably reinventing the entire wheel.

**Comment by Mrxx99** [comment]
What about having no mvvm by default in xplat template, but an option (--usemvvm) to include Community toolkit MVVM?

**Comment by stevemonaco** [comment]
If the template option still generates and wires a basic Mvvm Toolkit app similar to today, then that's sufficient.

**Comment by maxkatz6** [comment]
Having an additional option parameter makes sense, yes.
Even though It makes templates more complex.

**Comment by maxkatz6** [comment]
It's not optional https://github.com/AvaloniaUI/avalonia-dotnet-templates/pull/256
