### ISSUE TITLE
Only show Avalonia project items in Avalonia projects.

### ISSUE THREAD

**Issue by stevemonaco** [AvaloniaUI/avalonia-dotnet-templates#265]
### Is your feature request related to a problem? Please describe.

When using "Add New Item..." in Visual Studio, Avalonia-related items (eg. Avalonia UserControl) are always shown in the dialog for all C# projects, even if the user is trying to add something to a Console app. Other project templates, such as WPF and WinForms, do not do this.

Rider somehow already does this. It also shows Avalonia-related items in the Add context menu (VS doesn't, only shows in the dialog).

### Describe the solution you'd like

The Avalonia NuGet package adds a Project Capability called "Avalonia". If we add a constraint to the templates according to https://github.com/dotnet/templating/wiki/Constraints#project-capabilities then maybe VS will respect it. Untested at the moment. VS seems to respect the "tags" for "language" in template.json at least.

### Additional context

I can try to test + PR this but might take quite some time as I haven't built this repo or worked with .NET templating before.

From a community complaint.

**Comment by maxkatz6** [comment]
It works well in Console:
```
PS E:\Work\Projects\TrashBin\AvaloniaApplication1\ClassLibrary1> dotnet new avalonia.styles
Failed to instatiate template 'Avalonia Styles', the following constraints are not met:
   Project capabiltities: The template needs project capability 'Avalonia', and current project (E:\Work\Projects\TrashBin\AvaloniaApplication1\ClassLibrary1\ClassLibrary1.csproj) does not satisfy it.

To run the template anyway, use '--force' option:
   dotnet new avalonia.styles --force
```

And it's without issue in Avalonia project.
