### ISSUE TITLE
Templates should create a solution, not just a csproj

### ISSUE THREAD

**Issue by eagerestwolf** [AvaloniaUI/avalonia-dotnet-templates#27]
This is just some feedback, but the templates should follow the norm of creating a `csproj` and a `sln` like Microsoft's official templates do, instead of the user needing to create an empty solution with Visual Studio, Visual Studio for Mac or Xamarin, then creating a project with your template, and then add the created `csproj` to the empty solution created earlier again using Visual Studio, Visual Studio for Mac or Xamarin. Minor nag, I know, but I feel like it's just better practice. Additionally, for Visual Studio for Mac and Xamarin, adding a project to a solution isn't very intuitive, so it leads other developers to also follow poor practices.

**Comment by jkoritzinsky** [comment]
The default .NET CLI templates do not include a solution file. A solution file is only created if you create a project in VS or VS for Mac. The suggestion is to use the builtin `sln` template and the `dotnet sln` command.

**Comment by eagerestwolf** [comment]
Ah, was not aware of that. They must have changed that. I haven't really used .NET Core since the pre-1.0 days (back when we were still using JSON files and Visual Studio didn't even support .NET Core). Well, sorry for bothering you guys then.
