### ISSUE TITLE
Outdated templates for visual studio

### ISSUE THREAD

**Issue by DrDryg** [AvaloniaUI/avalonia-dotnet-templates#274]
### Is your feature request related to a problem? Please describe.

I want to create an avalonia application targeting web. I have the development tools installed in visual studio. But when creating projects I get an old avalonia version installed and 11.0.2 (I think) with .net 7 which is out of support. If upgrading to .net8 and upgrading avalonia I get issues that the namespaces in the web-app has changed. 

Seems to only be an issue with the cross platform solution. If I add a web application directly it works fine.

### Describe the solution you'd like

New updated templates.

**Comment by maxkatz6** [comment]
Avalonia console and VS templates were updated
