### ISSUE TITLE
[Question] Is there any thought on a template for program installation GUI?

### ISSUE THREAD

**Issue by thepra** [AvaloniaUI/avalonia-dotnet-templates#32]
Or do you have any insight on how to accomplish such a thing?

**Comment by grokys** [comment]
We have an extension for Visual Studio over at https://github.com/AvaloniaUI/AvaloniaVS

Outside Visual Studio though, I don't think a GUI for creating templates is really within our remit. If Visual Studio Code or some other IDE were to add such a thing to work with dotnet templates though, our templates should work.
