### ISSUE TITLE
VB version?

### ISSUE THREAD

**Issue by loops6972** [AvaloniaUI/avalonia-dotnet-templates#39]
Is there a possibility for a VB implementation of this template? I have a lot of vb apps that we are wanting to convert....

Or can the templates be modified locally to use VB as the underlying language? If so, where are these templates located after the install?

Thanks In Advance

**Comment by DrewNaylor** [comment]
Second this, I'd like to be able to easily create a new Avalonia project using VB. I'll probably try to do it myself since I've translated C# to VB before, but I'm almost burnt out from programming at the moment and it likely won't be good enough for a pull request. Looks easy enough to do, though.

**Comment by michieal** [comment]
> Second this, I'd like to be able to easily create a new Avalonia project using VB. I'll probably try to do it myself since I've translated C# to VB before, but I'm almost burnt out from programming at the moment and it likely won't be good enough for a pull request. Looks easy enough to do, though.

I agree, it would be nice to have this for VB.NET. I have a decade's worth of programs to translate from VB to C#... but, having the templates means I wouldn't have to do those translations; I'd just have to modify them to work with the new UI. (Which, would be epic!)

@DrewNaylor  Have you tried taking a base C# program that uses Avalonia and use ILSpy to convert the IL generated into VB? It might give you a viable workaround...

**Comment by DrewNaylor** [comment]
Haven't tried using ILSpy to convert it, but I just decided to call into VB.NET DLLs from the C# code for now since I know a little C# though I'm better at VB.NET than I am at C#. This probably won't help much for existing VB.NET projects or would be more complicated.

**Comment by michieal** [comment]
Create a new C# Avalonia UI project. build it. use IL Spy to open it. Change the language in IL Spy from C# to VB. Copy the code out into classes. You'll have the translation.

**Comment by Takoooooo** [comment]
Hello. Sorry, we don't plan to add support for VB currently thus closing the issue.

**Comment by mevdschee** [comment]
I converted the app template to VB, see: https://github.com/mevdschee/avalonia-vb-template-app

**Comment by DualBrain** [comment]
> Hello. Sorry, we don't plan to add support for VB currently thus closing the issue.

The video at https://youtu.be/9PZVjcp3Xxc?si=KLnPat1lghG5uQeQ strongly suggests otherwise...

**Comment by DualBrain** [comment]
And on https://avaloniaui.net/XPF I find...

> Does Avalonia XPF support applications developed with VB.NET?

> Yes. Avalonia XPF Works with all WPF applications, regardless of the language used. We have tested applications developed with C#, VB.NET and F#.

**Comment by DualBrain** [comment]
Not supported?????? It's really confusing when one can find the following in your own documentation (<https://docs.avaloniaui.net/docs/guides/building-cross-platform-applications/>) that states...

> Develop your apps in C#, F# or **VB.NET**. Existing code written with .NET can be seamlessly ported to Windows, Linux, macOS, iOS, Android and WebAssembly using Avalonia.

Has the stance changed since the statement was made in the last 2 years? If so, please enlighten us...

**Comment by maxkatz6** [comment]
@DualBrain supported. But there won't be templates.

**Comment by mevdschee** [comment]
> supported. But there won't be templates.

@DualBrain What does one have to do to get the missing templates included? Write them and do a PR? Are you open for that?

**Comment by MikeCodesDotNET** [comment]
> Has the stance changed since the statement was made in the last 2 years? If so, please enlighten us...

Our previous statement has remained unchanged. Avalonia is compatible with any .NET language, including VB.NET. This means you can develop Avalonia applications using VB.NET right now.

However, we currently do not plan to introduce official VB.NET project templates. This decision is based on several factors, notably the limited demand from a relatively small VB.NET user base and the resource commitment required to maintain additional templates indefinitely. 

We are constantly monitoring the landscape of .NET development. Should there be a substantial shift in Microsoft's investment in VB.NET and a corresponding surge in community demand, we would certainly consider revisiting our decision.

**Comment by grokys** [comment]
Note that `dotnet` templates are simply NuGet packages and as such if you or the community wanted to create and maintain some unofficial VB templates, we'd be happy to point people to them.

**Comment by DualBrain** [comment]
Feel free to take a look at some VB templates for Avalonia UI that are available (as source) over at https://github.com/CommunityVB/Templates/avalonia

Will eventually make these available as a nuget package; but they are available now in source and certainly could use some testing/feedback. After some testing/feedback, will create the desired nuget package(s).

**Comment by DualBrain** [comment]
> Page not found.

Sorry about that, I typed in the URL manually and should have just entered the main Templates repo... with that said, here's a corrected link.

https://github.com/CommunityVB/Templates/tree/main/src/avalonia
