### ISSUE TITLE
dotnet new avalonia.mvvm template could not build

### ISSUE THREAD

**Issue by alan0428a** [AvaloniaUI/avalonia-dotnet-templates#42]
```
using System;
using Avalonia;
using Avalonia.Controls.ApplicationLifetimes;
using Avalonia.ReactiveUI;

namespace dotnet
{
    class Program
    {
        // Initialization code. Don't use any Avalonia, third-party APIs or any
        // SynchronizationContext-reliant code before AppMain is called: things aren't initialized
        // yet and stuff might break.
        public static void Main(string[] args) => BuildAvaloniaApp()
            .StartWithClassicDesktopLifetime(args);

        // Avalonia configuration, don't remove; also used by visual designer.
        public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .LogToDebug()
                .UseReactiveUI();
    }
}
```

The template code generated by "dotnet new avalonia.mvvm" is missing `using Avalonia.Logging.Serilog;` at Program.cs, which makes `LogToDebug()` fails to build.

**Comment by bykka** [comment]
Have the same issue:

'AppBuilder' does not contain a definition for 'LogToDebug' and no accessible extension method 'LogToDebug' accepting a first argument of type 'AppBuilder' could be found (are you missing a using directive or an assembly reference?) [MyAvalonApp]

File: Program.cs
Line: 20

**Comment by CodeOhms** [comment]
When will this be fixed?

**Comment by grokys** [comment]
Looks like this was a problem introduced by https://github.com/AvaloniaUI/avalonia-dotnet-templates/pull/38 and wrongly merged. Reverting now.

**Comment by grokys** [comment]
Reverted.
