### ISSUE TITLE
Don't add `.idea` to `.gitignore`

### ISSUE THREAD

**Issue by nils-a** [AvaloniaUI/avalonia-dotnet-templates#61]
When creating a new project from the mvvm-template a default `.gitignore` is deployed that contains an ignore for `.idea`.

Please don't add `.idea` in the ignores: When Rider creates an `.idea` folder, it will place a `.gitignore` in there, which will contain the "correct" ignores for working with Rider.

**Comment by ForNeVeR** [comment]
_(Disclaimer: I am the technical lead of the JetBrains Rider project, but what I'm stating here is more of an opinion. I've discussed it with my colleagues, and there are alternate opinions on this matter. They may also join this thread if they wish._

_Also, I've been asked for advice by the Avalonia folks.)_

I'd say that it's better to just ignore everything in `.idea` by default, and explicitly add only required stuff if you really want to. Rider usually moves most (if not all) of the explicitly shared stuff (such as shared run configurations or team-shared settings) out of `.idea`. So there's less and less sense to have anything in `.idea` shared with anyone (and thus less sense to not ignore this directory).

You aren't forced to follow this policy, for sure (and the default `.gitignore` in this directory would help you to filter out the most volatile stuff). But that's what I do in my open-source projects and what I would recommend.

There are still some samples of settings you would like to share (say, shared dictionaries for spellchecking); these I usually add manually as they don't require too much bookkeeping.
