### ISSUE TITLE
Include DataGrid theme in App.axaml for app & app-mvvm?

### ISSUE THREAD

**Issue by p-m-j** [AvaloniaUI/avalonia-dotnet-templates#87]
There may be good reasons not to do this? But would certainly have saved me some confusion

```xml
 <Application.Styles>
    <FluentTheme Mode="Light" />
    <StyleInclude Source="avares://Avalonia.Controls.DataGrid/Themes/Fluent.xaml"/>
 </Application.Styles>
```

Edit: Ahh perhaps because there is no package ref for Avalonia.Controls.DataGrid, it's brought in by Avalonia.Diagnostics for debug build config?

**Comment by Takoooooo** [comment]
Yeah, it isn't used directly in app\app-mvvm templates that's why we don't include this style by default. We only include by default the stuff that is needed to run this template.
